// <auto-generated />
using System;
using Ewaste_Vs2022.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ewaste_Vs2022.Migrations
{
    [DbContext(typeof(EwasteDbContext))]
    [Migration("20220221170536_Ewastethird")]
    partial class Ewastethird
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ewaste_Vs2022.Models.AreaMaster", b =>
                {
                    b.Property<int>("Aid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Aid"), 1L, 1);

                    b.Property<string>("Areaname")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Aid");

                    b.ToTable("AreaMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.CartMaster", b =>
                {
                    b.Property<int>("Cartid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cartid"), 1L, 1);

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<int>("SCQty")
                        .HasColumnType("int");

                    b.Property<int>("SCid")
                        .HasColumnType("int");

                    b.HasKey("Cartid");

                    b.ToTable("CartMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.ComplainMaster", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cid"), 1L, 1);

                    b.Property<string>("Cdetails")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.HasKey("Cid");

                    b.ToTable("ComplainMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.DriverMaster", b =>
                {
                    b.Property<int>("Drvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Drvid"), 1L, 1);

                    b.Property<int>("DAid")
                        .HasColumnType("int");

                    b.Property<string>("Daddress")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Ddob")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Dgender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Dimage")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Dlicimage")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Dphone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Dvehiclenumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.HasKey("Drvid");

                    b.ToTable("DriverMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.FeedbackMaster", b =>
                {
                    b.Property<int>("Fid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fid"), 1L, 1);

                    b.Property<string>("ExperienceRate")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Feedbackdate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Feedbackdesc")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.HasKey("Fid");

                    b.ToTable("FeedbackMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.OrderMaster", b =>
                {
                    b.Property<int>("Ordid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ordid"), 1L, 1);

                    b.Property<int>("Areaid")
                        .HasColumnType("int");

                    b.Property<int>("Drvid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Orddate")
                        .HasColumnType("DateTime2");

                    b.Property<decimal>("Ordgrandtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Ordpaymentmode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Ordstatus")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Ordtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.HasKey("Ordid");

                    b.ToTable("OrderMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.PersonMaster", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"), 1L, 1);

                    b.Property<string>("Paddress")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Panswer")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Pdob")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Pemail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pgender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Pimage")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ppassword")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pphone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Pqid")
                        .HasColumnType("int");

                    b.Property<int>("Proleid")
                        .HasColumnType("int");

                    b.HasKey("Pid");

                    b.ToTable("PersonMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.ProductCategoryMaster", b =>
                {
                    b.Property<int>("Catid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Catid"), 1L, 1);

                    b.Property<string>("Catimage")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Catname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Catid");

                    b.ToTable("ProductCategoryMasters");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.ProductSubCategory", b =>
                {
                    b.Property<int>("SCid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SCid"), 1L, 1);

                    b.Property<int>("Catid")
                        .HasColumnType("int");

                    b.Property<string>("SCdesc")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SCimage")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SCname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SCpriceperunit")
                        .HasColumnType("int");

                    b.HasKey("SCid");

                    b.ToTable("ProductSubCategories");
                });

            modelBuilder.Entity("Ewaste_Vs2022.Models.QuestionMaster", b =>
                {
                    b.Property<int>("Qid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Qid"), 1L, 1);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Qid");

                    b.ToTable("QuestionMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
